super_resolution:

  RealESRGAN_x4plus:
    file: RealESRGAN_x4plus.pth
    scale: 4
    type: realesrgan

  RealESRGAN_x2plus:
    file: RealESRGAN_x2plus.pth
    scale: 2
    type: realesrgan

frame_interpolation:

  rife:
    file: rife.pkl
    type: rife